const CarsData = [
  {
    id: 0,
    image: [
      '/src/assets/images/car1000x1000x0001.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'Mercedes',
    price: '$75,000',
    make: 'Toyota',
    model: 'Benz',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: true,
    newArrival: true,
    onSale: false,
    topRated: true,
  },
  {
    id: 1,
    image: [
      '/src/assets/images/car1000x1000x0002.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],

    name: 'Cadillac Escalade',
    price: '$70,000',
    make: 'Cadillac',
    model: 'Escalade',
    year: '2015',
    mileage: '12000 km',
    seller: 'XYZ Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: true,
    newArrival: false,
    onSale: false,
    topRated: true,
  },
  {
    id: 2,
    image: [
      '/src/assets/images/car1000x1000x0003.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'Toyota RAV4',
    price: '$35,000',
    make: 'Toyota',
    model: 'RAV4',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: true,
    newArrival: true,
    onSale: false,
    topRated: true,
  },
  {
    id: 3,
    image: [
      '/src/assets/images/car1000x1000x0004.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'Nissan Rogue',
    price: '$22,000',
    make: 'Nissan',
    model: 'Rogue',
    year: '2015',
    mileage: '12000 km',
    seller: 'XYZ Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: true,
    newArrival: false,
    onSale: false,
    topRated: true,
  },
  {
    id: 4,
    image: [
      '/src/assets/images/car1000x1000x0005.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'Nissan Centra',
    price: '$18,000',
    make: 'Nissan',
    model: 'Centra',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: true,
    newArrival: true,
    onSale: false,
    topRated: true,
  },
  {
    id: 5,
    image: [
      '/src/assets/images/car1000x1000x0006.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'Toyota Land Cruiser',
    price: '$50,000',
    make: 'Toyota',
    model: 'Corolla',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: true,
    newArrival: false,
    onSale: false,
    topRated: true,
  },
  {
    id: 6,
    image: [
      '/src/assets/images/car1000x1000x0007.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'Tesla Model S',
    price: 30000,
    make: 'Tesla',
    model: 'Model S',
    year: '2015',
    mileage: '12000 km',
    seller: 'XYZ Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: true,
    newArrival: true,
    onSale: false,
    topRated: true,
  },
  {
    id: 7,
    image: [
      '/src/assets/images/car1000x1000x0008.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'Mercedes',
    price: '$50,000',
    make: 'Mercedes',
    model: 'Benz',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: false,
    onSale: false,
    topRated: false,
  },
  {
    id: 8,
    image: [
      '/src/assets/images/car1000x1000x0009.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'Mercedes Benz',
    price: '$75,000',
    make: 'Mercedes',
    model: 'Benz',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: true,
    onSale: false,
    topRated: false,
  },
  {
    id: 9,
    image: [
      '/src/assets/images/car1000x1000x0010.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'Toyota Corolla',
    price: '$24,000',
    make: 'Toyota',
    model: 'Corolla',
    year: '2015',
    mileage: '12000 km',
    seller: 'XYZ Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: false,
    onSale: false,
    topRated: false,
  },
  {
    id: 10,
    image: [
      '/src/assets/images/car1000x1000x0011.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'Nissan Rogue',
    price: '$20,000',
    make: 'Nissan',
    model: 'Rogue',
    year: '2015',
    mileage: '12000 km',
    seller: 'XYZ Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: true,
    onSale: false,
    topRated: false,
  },
  {
    id: 11,
    image: [
      '/src/assets/images/car1000x1000x0012.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'BMW',
    price: '$50,000',
    make: 'BMW',
    model: 'M2',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: false,
    onSale: false,
    topRated: false,
  },
  {
    id: 12,
    image: [
      '/src/assets/images/car1000x1000x0013.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'Mercedes',
    price: '$60,000',
    make: 'Mercedes',
    model: 'Benz',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: true,
    onSale: false,
    topRated: false,
  },
  {
    id: 13,
    image: [
      '/src/assets/images/car1000x1000x0014.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'BMW',
    price: '$55,000',
    make: 'BMW',
    model: 'M2',
    year: '2015',
    mileage: '12000 km',
    seller: 'XYZ Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: false,
    onSale: false,
    topRated: false,
  },
  {
    id: 14,
    image: [
      '/src/assets/images/car1000x1000x0015.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'Mercedes',
    price: '$60,000',
    make: 'Mercedes',
    model: 'Benz',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: true,
    onSale: false,
    topRated: false,
  },
  {
    id: 15,
    image: [
      '/src/assets/images/car1000x1000x0016.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'Mercedes',
    price: '$60,000',
    make: 'Mercedes',
    model: 'Benz',
    year: '2015',
    mileage: '12000 km',
    seller: 'XYZ Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: false,
    onSale: false,
    topRated: false,
  },
  {
    id: 16,
    image: [
      '/src/assets/images/car1000x1000x0017.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'BMW',
    price: '$40,000',
    make: 'BMW',
    model: 'M3',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: false,
    onSale: false,
    topRated: false,
  },
  {
    id: 17,
    image: [
      '/src/assets/images/car1000x1000x0018.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'Toyota Corolla',
    price: '$25,000',
    make: 'Toyota',
    model: 'Corolla',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: false,
    onSale: false,
    topRated: false,
  },
  {
    id: 18,
    image: [
      '/src/assets/images/car1000x1000x0019.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'Cadillac',
    price: '$55,000',
    make: 'Cadillac',
    model: 'Escalade',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: false,
    onSale: false,
    topRated: false,
  },
  {
    id: 19,
    image: [
      '/src/assets/images/car1000x1000x0020.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'Mercedes',
    price: '$75,000',
    make: 'Mercedes',
    model: 'Benz',
    year: '2015',
    mileage: '12000 km',
    seller: 'XYZ Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: false,
    onSale: false,
    topRated: false,
  },
  {
    id: 20,
    image: [
      '/src/assets/images/car1000x1000x0021.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'Toyota RAV4',
    price: '$25,000',
    make: 'Toyota',
    model: 'RAV4',
    year: '2015',
    mileage: '12000 km',
    seller: 'XYZ Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: true,
    onSale: false,
    topRated: false,
  },
  {
    id: 21,
    image: [
      '/src/assets/images/car1000x1000x0022.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'Honda',
    price: '$25,000',
    make: 'Honda',
    model: 'Civic',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: true,
    onSale: false,
    topRated: false,
  },
  {
    id: 22,
    image: [
      '/src/assets/images/car1000x1000x0023.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'Mitsubishi',
    price: '$22,000',
    make: 'Mitsubishi',
    model: 'Attrage',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: true,
    onSale: false,
    topRated: false,
  },
  {
    id: 23,
    image: [
      '/src/assets/images/car1000x1000x0024.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'Hyundai Tucson',
    price: '$20,000',
    make: 'Hyundai',
    model: 'Tucson',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: true,
    onSale: false,
    topRated: false,
  },
  {
    id: 24,
    image: [
      '/src/assets/images/car1000x1000x0025.png',
      '/src/assets/images/cint0001.png',
      '/src/assets/images/cint0002.png',
      '/src/assets/images/cint0003.png',
      '/src/assets/images/cint0004.png',
    ],
    name: 'Nissan Pathfinder',
    price: '$32,000',
    make: 'Nissan',
    model: 'Pathfinder',
    year: '2015',
    mileage: '12000 km',
    seller: 'ABC Auto',
    bodyStyle: 'Coup',
    extcolor: 'Black',
    intcolor: 'Silver',
    transmission: 'Manual',
    driveline: '4WD',
    feultype: 'Gasoline',
    mpg: '20 MPG',
    featured: false,
    newArrival: false,
    onSale: false,
    topRated: false,
  },
];

export default CarsData;
